import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect } from "react";
import LoginScreen from "../components/LoginScreen";
import QuizScreen from "../components/QuizScreen";
import useLocalStorage from "../hooks/useLocalStorage";

const Home: NextPage = () => {
  const [username, setUsername] = useLocalStorage("username", "");

  const handleSubmit = (name: string) => (e: React.SyntheticEvent) => {
    e.preventDefault();

    name && setUsername(name);
  };

  useEffect(() => {
    !username && localStorage.clear();
  }, [username]);

  return (
    <div className="flex min-h-screen flex-col bg-gray-800">
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="bg-gray-600 p-5">
        <h1 className="text-center text-3xl font-extrabold text-green-100">
          Quiz App
        </h1>
      </header>

      {/* Main */}
      <main className="relative flex flex-1 flex-col items-center justify-center  p-4 font-sans">
        {username && (
          <div className="absolute top-0 mt-2 mr-2 flex items-center justify-center gap-4 rounded-md bg-gray-700 px-3 py-2">
            <p className="text-center text-xl text-green-400">👤 {username}</p>
            <button
              className="text-center text-xl text-red-400"
              onClick={() => setUsername("")}
            >
              ❌
            </button>
          </div>
        )}

        {username ? (
          <QuizScreen />
        ) : (
          <LoginScreen handleSubmit={handleSubmit} />
        )}
      </main>
    </div>
  );
};

export default Home;
